version = 1

test_patterns = ["*/test/**"]

exclude_patterns = []

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2016"
  module_system = "commonjs"
  environment = [
    "nodejs",
  ]