name: "AWS SSM command manager"
author: "Nikita Stepanov <nstepanov@preludedynamics.com>"

branding:
  icon: "arrow-up-right"
  color: "orange"

description: "Remote EC2 bash command execution and getting the result."

inputs:
  mode:
    required: true
    description: "Choose read or result mode"
  command-id:
    required: false
    description: "Command id to check result. Uses only for result mode"
  aws-access-key-id:
    required: true
    description: "AWS access key id"
  aws-secret-access-key:
    required: true
    description: "AWS secret access key"
  aws-region:
    required: true
    description: "Where EC2 instance is"
  instance-ids:
    required: true
    description: "AWS EC2 Instance id or ids"
  command:
    required: false
    description: "Bash command you want to execute. Uses only for send mode"
  working-directory:
    required: false
    description: "Command execution location. Uses only for send mode"
  comment:
    required: false
    description: "Comment for command"
    default: "Executed by Github Actions"

runs:
  using: "node12"
  main: "dist/index.js"
